version: 2.1

jobs:
  build-and-test:
    docker:
      # Imagen con Java 21 + Navegadores (Chrome/Edge)
      - image: cimg/openjdk:21.0-browsers
      
      # Base de Datos MySQL
      - image: cimg/mysql:8.0
        environment:
          MYSQL_DATABASE: calidad
          MYSQL_ROOT_PASSWORD: "123456"

    steps:
      - checkout
      - run:
          name: Instalar Cliente MySQL
          command: sudo apt-get update && sudo apt-get install -y default-mysql-client
      - run:
          name: Esperar a que MySQL inicie
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Cargar Schema de Base de Datos
          command: |
            mysql -h 127.0.0.1 -u root -p123456 calidad < src/test/resources/schema.sql
      - run:
          name: Compilar Proyecto
          command: mvn -B -DskipTests clean package
      
      # Ejecución de Pruebas
      - run:
          name: Test Unitario - Calculadora
          command: mvn test -Dtest=com.calidad.CalculadoraTest
      - run:
          name: Test Unitario - Mockito (UserService, Login, Dependency)
          command: mvn test -Dtest=com.calidad.login.UserServiceTest,com.calidad.login.LoginServiceTest,com.calidad.DependecyTest
      - run:
          name: Test Integración - DBUnit
          command: mvn test -Dtest=com.calidad.login.integracion.UserServiceTest
      - run:
          name: Test Funcional - CRUD MERN
          command: mvn test -Dtest=com.calidad.funcionales.CRUDFuncionalTest
      - run:
          name: Test Funcional - Uady Virtual
          command: mvn test -Dtest=com.calidad.funcionales.UadyVirtualTest
      
      - store_test_results:
          path: target/surefire-reports

workflows:
  sample:
    jobs:
      - build-and-test